### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by drj11** [pykale/pykale#23]
Make sure it works!

Remove torch-cluster? (and put it documentation that you only need it for torch-geometric).

**Comment by RaivoKoot** [comment]
I know that when you pip install torch, it automatically installs numpy and other dependencies that it has. Because of that, we could remove numpy, for example, from our requirements.txt. Do you have any experience knowing whether it is normal to just remove those packages from requirements.txt which would be auto-installed anyways by other packages in requirements.txt? Seems to me like the thing to do.

**Comment by drj11** [comment]
if you also use `numpy` directly, keep it in. If you don't otherwise touch `numpy`, then leave it out and let `torch` install it implicitly.

**Comment by drj11** [comment]
currently I have removed torch-cluster, but the relevant dependencies should go in a separate requirements file.

When it becomes a public package, i want to make `torch-cluster` an optional dependency, so you can go:

    pip install pykale[cluster]

to get pykale _and_ the dependencies you need for clustering.

**Comment by RaivoKoot** [comment]
Nice. I've just tried doing a fresh install of the package using the requirements file and it all works. Ran your import test as well and it works. 

I noticed however that importing just kale doesn't really test for anything, because it works even with no packages installed at all.

If we add this instead however, importing all files
```
import kale
from kale.embed import image_cnn, mpca, positional_encoding, attention_cnn
from kale.loaddata import cifar_access, dataset_access, digits_access, mnistm, multi_domain, sampler, usps, videos
from kale.pipeline import domain_adapter
from kale.predict import class_domain_nets, isonet, losses
from kale.prepdata import image_transform, prep_cmr, tensor_reshape, video_transform
from kale.utils import csv_logger, logger, seed

""" These only work with the optional graph libraries
from kale.embed import gcn, gripnet
"""

print('kale imported')
```
then it tests it properly. I think what we might wanna do is just note that the user needs to install torch manually. Then, we can just add all libraries to `requirements.txt`

**Comment by RaivoKoot** [comment]
Have added these to requirements.txt as well though for the above to work.
```
# Need to specify version
pytorch-lightning
scikit-image
tensorly
```
These are libraries used by some of pykales modules.

**Comment by haipinglu** [comment]
PyPI and conda ready.
