### ISSUE TITLE
Support for Python 3.7 and above

### ISSUE THREAD

**Issue by bobturneruk** [pykale/pykale#316]
# 🚀 Feature Request

Current CI tests would fail for Python 3.7 or above. We should support more recent versions of Python.

## Motivation

Python 3.7 is the earliest version of Python still getting fixes of any kind.

## Pitch

Python versions greater than 3.7 should be added to the CI:

https://github.com/pykale/pykale/blob/3724843b3a3abad83be8b32bde0ca4bacfbddea8/.github/workflows/test.yml#L22

The resulting failures should be debugged and dependencies updated etc. as needed.

**Comment by haipinglu** [comment]
@pz-white This might be a good example that we can learn from to "upgrade" graph-related modules: https://colab.research.google.com/drive/14GPEIR7uRz50K9E_p9OUwjSOig0ZOB_E from which we can see the PyG installation has become more professional: https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html

**Comment by pz-white** [comment]
@haipinglu Thanks, I'll check how to transfer it.

**Comment by XianyuanLiu** [comment]
PR #246 shows [zip file](https://drive.google.com/file/d/1U4D23R8u8MJX9KVKb92bZZX-tbpKWtga/view) cannot be downloaded and unzipped through torchvision.datasets.utils.download_file_from_google_drive in Torch 1.9.1 and Torchvision 0.10.1. But it works in the newer versions, e.g. Torch 1.10.0/1.10.2/1.11.0 and Torchvision 0.11.0/ 0.11.3/0.12.0.

The simplest solution is to upgrade PyKale to provide support for the latest version of Python/PyTorch/Torchvision/PyTorch Lightning. Since the latest PyTorch does not support Python 3.6, we can also remove the support for Python 3.6.
