### ISSUE TITLE
[Refactor] Pytorch Lightning for Future Examples

### ISSUE THREAD

**Issue by RaivoKoot** [pykale/pykale#42]
### A clear and concise description of what you wish to refactor
I propose that for any future examples we create where we train a model, we **always** use [Pytorch Lightning](https://www.pytorchlightning.ai/).  Lightning's structure is super clean and understandable and leaves out **huge** amounts of boilerplate code. This boilerplate code makes it much harder for users to find the lines of code they really care about. I think lightning is important because it forces each of us to create very minimal and clean examples.  
  
I think if we don't do this, we will have a problem in the future where all of our examples/tutorials are too messy.
This is because right now we are all writing our training systems in very different ways. Sometimes cleaner, sometimes messier, and different every time.  
  
It would be good if every examples follows the same uniform code structure. This way it will be very easy for users to learn about the different examples because they spend minimal time understanding unimportant technical code. It would be easier for users to learn about pykale through our examples like this.  
  
  
Besides, after not using it for the past 6 months, I've started using lightning again now and it is absolutely amazing 😁. 

### Modules that will be modified
Future examples 
### Impact on code structure
All examples that train models will have a uniform structure
### Impact on speed
None
### Will this be a breaking change
No because this only affects examples and nothing depends on examples

#### Notes
Let me know if I did something wrong in the labeling or organizing of this issue. Also, we can discuss this issue in the next meeting.

**Comment by haipinglu** [comment]
Yes, this is an important issue for all of us to reach a consensus (across medical imaging, graph learning and CV). I agree the core principle of **standardisation** and **minimalism**, which could be the key pitch of PyKale. Our pipeline-based API should make this more feasible as well and the recent effort in linting is also along this direction.

One issue is about non-deep learning flows. We need to find out
- whether they can be fit in Pytorch Lightning (PL) well,
- whether a PL implementation will be beneficial or detrimental, and
- if PL does not fit, whether we can sort out something similar, as a key feature of PyKale.

When you review PR #41, you may also note down existing problems or potential changes for discussion, by creating a [new discussion](https://github.com/pykale/pykale/discussions) or issue or Google doc. Many thanks. 

If necessary, we could also make changes to our current examples. 

On the management of this issue
- You could select the project (v0.1.0) for this issue so that it will be auto-added to our active project board, which should contain all matters to discuss in our bi-weekly meetings to keep track (I did it for this one but you could do in future).
- I agree with the label.

**Comment by RaivoKoot** [comment]
Nice thanks for the management tips. I will continue this in discussions.
